container:
  image: cirrusci/flutter:stable

#test_task:
#  pub_cache:
#    folder: ~/.pub-cache
#  test_script: flutter test

build_task:
  build_script:
    - flutter config --enable-web
    - flutter pub get
    - flutter pub upgrade
    - flutter pub run build_runner build
    - flutter build web --release --no-sound-null-safety
  binaries_artifacts:
    path: "build/web/**"
