name: housing
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_countdown_timer: ^4.0.0
  url_launcher: ^6.0.2
  dio: ^4.0.0
  json_annotation: ^4.0.1
  flutter_dotenv: ^4.0.0-nullsafety.0
  pretty_dio_logger: ^1.2.0-beta-1
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  email_validator: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.2
  json_serializable: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - config.env
    - res/logo_200x140.png
    - res/logo_400x280.png

  fonts:
    - family: MyIcons
      fonts:
        - asset: res/MyIcons.ttf
